<?php
# This file is automatically generated by blog.py when building
# This static copy in src/ is just there to make it clear how the file will look like once built.
$all_articles = array(
	'post1' => array(
		'url' => 'https://...',
		'title' => 'My first post ever!'
	),
	'post2' => array(
		'url' => 'https://...',
		'title' => 'My second post on this blog'
	),
	'post3' => array(
		'url' => 'https://...',
		'title' => 'And now the post that comes after that'
	)
);
?>